"""phase4_batch_genealogy

Revision ID: 157baa54b911
Revises: '217f4b7a118f'
Create Date: 2026-09-07 13:22:14.748790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157baa54b911'
down_revision: Union[str, None] = '217f4b7a118f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_batch_id', sa.String(length=100), nullable=False),
    sa.Column('child_batch_id', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_transferred_kg', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('parent_batch_id != child_batch_id', name='ck_prevent_self_parenting'),
    sa.ForeignKeyConstraint(['child_batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['batches.batch_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_batch_id', 'child_batch_id', name='uq_parent_child_relationship')
    )
    op.create_index(op.f('ix_batch_relationships_child_batch_id'), 'batch_relationships', ['child_batch_id'], unique=False)
    op.create_index(op.f('ix_batch_relationships_id'), 'batch_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_batch_relationships_parent_batch_id'), 'batch_relationships', ['parent_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_relationships_parent_batch_id'), table_name='batch_relationships')
    op.drop_index(op.f('ix_batch_relationships_id'), table_name='batch_relationships')
    op.drop_index(op.f('ix_batch_relationships_child_batch_id'), table_name='batch_relationships')
    op.drop_table('batch_relationships')
    # ### end Alembic commands ###
